name: V2Ray Proxy Debugger

on:
  workflow_dispatch: # فقط اجرای دستی برای دیباگ

jobs:
  debug-single-proxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests

      - name: Make tools executable
        run: chmod +x ./base/*
      
      - name: Run Single Proxy Debug Script
        env:
          # --- تغییر اصلی: پروکسی مستقیماً اینجا تعریف شده ---
          PROXY_TO_TEST: 'vless://7c9e3c1d-a360-4429-9189-e45a98de7fde@[::ffff:45.142.120.8]:443?encryption=none&security=tls&sni=mail.ski1plag.ir&alpn=h2%2Chttp%2F1.1&fp=random&type=ws&host=mail.ski1plag.ir&path=%2Fupload'
        run: python -u scripts/02_test_proxies.py
