name: V2Ray Proxy Auto Tester

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # ما به یک توکن دسترسی شخصی نیاز داریم تا بتوانیم pull و push را با هم انجام دهیم
        # این توکن به صورت خودکار توسط گیت‌هاب ساخته و استفاده می‌شود
        uses: actions/checkout@v4
        with:
          # این خط اطمینان می‌دهد که ما با اطلاعات کامل گیت کار می‌کنیم
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Fetch Proxies Script
        run: python -u scripts/01_fetch_proxies.py

      - name: Run GitHub Proxy Tester Script
        run: python -u scripts/02_test_github.py
      
      - name: Commit and push results
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # --- تغییرات اصلی اینجا هستند ---
          # 1. آخرین تغییرات را از ریپازیتوری می‌گیریم
          # استراتژی "ours" در صورت وجود تداخل، تغییرات محلی ما را در اولویت قرار می‌دهد
          git pull origin main --strategy=ours
          
          # 2. فایل‌ها را برای کامیت اضافه می‌کنیم
          git add -f output/
          
          # 3. کامیت و پوش می‌کنیم
          if ! git diff --staged --quiet; then
            echo "Changes found, committing..."
            git commit -m "✅ Update proxy lists | $(date -u)"
            git push
          else
            echo "No changes to commit."
          fi
