name: V2Ray Proxy Auto Tester
on:
  workflow_dispatch: # فعلا فقط دستی برای تست
permissions:
  contents: write
jobs:
  test-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # --- تغییر اصلی: نصب کتابخانه‌های صحیح ---
      - name: Install dependencies
        run: pip install curl_cffi requests PySocks
      - name: Make tools executable
        run: chmod +x ./base/*
      - name: Run Proxy Tester Script
        env:
          # پروکسی سالم شما برای دیباگ
          PROXY_TO_TEST: 'vless://7c9e3c1d-a360-4429-9189-e45a98de7fde@[::ffff:45.142.120.8]:443?encryption=none&security=tls&sni=mail.ski1plag.ir&alpn=h2%2Chttp%2F1.1&fp=random&type=ws&host=mail.ski1plag.ir&path=%2Fupload'
        run: python -u scripts/02_test_proxies.py
