name: V2Ray Proxy Auto Tester
on:
  schedule:
    - cron: '15 */3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests curl_cffi PySocks
      - name: Make tools executable
        run: chmod +x ./base/*
      - run: python -u scripts/01_fetch_proxies.py
      - run: python -u scripts/02_test_proxies.py
      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Proxy Tester)"
          git add -f output/
          if ! git diff --staged --quiet; then
            COMMIT_MESSAGE="feat(proxies): Update active proxy lists on $(date -u)"
            PROXY_COUNT=$(cat output/github_all.txt 2>/dev/null | wc -l)
            COMMIT_DETAILS="Total active proxies: $PROXY_COUNT"
            git commit -m "$COMMIT_MESSAGE" -m "$COMMIT_DETAILS"
            git push
          else
            echo "No changes to commit."
          fi
