name: Update Core Tools

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create base directory if not exists
        run: mkdir -p base

      # --- مرحله آپدیت تستر Xray (x-ray-ping) ---
      - name: Update Xray-Tester (x-ray-ping)
        run: |
          TOOL_NAME="xray-tester"
          REPO="William-An/x-ray-ping"
          echo "Downloading latest version of $TOOL_NAME from $REPO..."
          
          # --- تغییر اصلی: استفاده مستقیم از لینک latest ---
          DOWNLOAD_URL="https://github.com/$REPO/releases/latest/download/x-ray-ping_linux_amd64.tar.gz"
          
          curl -L -o tool.tar.gz "$DOWNLOAD_URL"
          tar -xzf tool.tar.gz
          # فایل اجرایی را به پوشه base منتقل و نام آن را تغییر می‌دهیم
          mv x-ray-ping "base/$TOOL_NAME"
          chmod +x "base/$TOOL_NAME"
          rm tool.tar.gz
          
          echo "$TOOL_NAME has been updated/installed."

      # --- مرحله آپدیت کلاینت Hysteria 2 ---
      - name: Update Hysteria-Client
        run: |
          TOOL_NAME="hysteria-client"
          REPO="apernet/hysteria"
          echo "Downloading latest version of $TOOL_NAME from $REPO..."

          # --- تغییر اصلی: استفاده مستقیم از لینک latest ---
          DOWNLOAD_URL="https://github.com/$REPO/releases/latest/download/hysteria-linux-amd64"

          curl -L -f -o "base/$TOOL_NAME" "$DOWNLOAD_URL"
          chmod +x "base/$TOOL_NAME"

          echo "$TOOL_NAME has been updated/installed."

      # --- مرحله کامیت کردن تغییرات ---
      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Tool Updater)"
          # چک می‌کند آیا تغییری در پوشه base برای کامیت وجود دارد یا نه
          if ! git diff --quiet HEAD -- base/; then
            git add base/
            git commit -m "chore(base): Update core tools"
            git push
          else
            echo "No tool updates to commit."
          fi
