name: Update Core Tools

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create base directory if not exists
        run: mkdir -p base

      - name: Update Xray-Core
        id: update_xray
        run: |
          TOOL_NAME="xray-core"
          REPO="XTLS/Xray-core"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates..."
          LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          echo "Latest version is: $LATEST_TAG"

          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current version is: $CURRENT_VERSION"
          
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading..."
            DOWNLOAD_URL="https://github.com/$REPO/releases/download/${LATEST_TAG}/Xray-linux-64.zip"
            
            curl -L -o xray.zip "$DOWNLOAD_URL"
            unzip -o xray.zip xray -d .
            mv xray "base/$TOOL_NAME"
            chmod +x "base/$TOOL_NAME"
            rm xray.zip
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME updated."
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Hysteria-Client
        id: update_hysteria
        run: |
          # (کد این بخش که برای Hysteria به درستی کار می‌کرد، بدون تغییر باقی می‌ماند)
          TOOL_NAME="hysteria-client"
          REPO="apernet/hysteria"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates..."
          LATEST_TAG=$(curl -sI "https://github.com/$REPO/releases/latest" | grep -i "location:" | awk -F'/' '{print $NF}' | tr -d '\r')
          echo "Latest version is: $LATEST_TAG"

          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current version is: $CURRENT_VERSION"

          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading..."
            DOWNLOAD_URL="https://github.com/$REPO/releases/download/${LATEST_TAG}/hysteria-linux-amd64"
            curl -L -f -o "base/$TOOL_NAME" "$DOWNLOAD_URL"
            chmod +x "base/$TOOL_NAME"
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME updated."
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updates
        if: steps.update_xray.outputs.updated == 'true' || steps.update_hysteria.outputs.updated == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Tool Updater)"
          git add base/
          git commit -m "chore(base): Update core tools"
          git push
