name: Update Core Tools

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create base directory if not exists
        run: mkdir -p base

      # --- مرحله آپدیت تستر Xray (x-ray-ping) ---
      - name: Update Xray-Tester (x-ray-ping)
        id: update_xray
        run: |
          TOOL_NAME="xray-tester"
          REPO="William-An/x-ray-ping"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates from $REPO..."
          # --- تغییر اصلی: استفاده از jq برای استخراج تگ ---
          LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          echo "Latest version on GitHub is: $LATEST_TAG"

          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current local version is: $CURRENT_VERSION"
          
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading $LATEST_TAG..."
            DOWNLOAD_URL="https://github.com/$REPO/releases/download/${LATEST_TAG}/x-ray-ping_linux_amd64.tar.gz"
            
            curl -L -o tool.tar.gz "$DOWNLOAD_URL"
            tar -xzf tool.tar.gz
            mv x-ray-ping "base/$TOOL_NAME"
            chmod +x "base/$TOOL_NAME"
            rm tool.tar.gz
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME has been updated to $LATEST_TAG"
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      # --- مرحله آپدیت کلاینت Hysteria 2 ---
      - name: Update Hysteria-Client
        id: update_hysteria
        run: |
          TOOL_NAME="hysteria-client"
          REPO="apernet/hysteria"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates from $REPO..."
          # --- تغییر اصلی: استفاده از jq برای استخراج تگ ---
          LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          echo "Latest version on GitHub is: $LATEST_TAG"
          
          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current local version is: $CURRENT_VERSION"
          
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading $LATEST_TAG..."
            DOWNLOAD_URL="https://github.com/$REPO/releases/download/${LATEST_TAG}/hysteria-linux-amd64"

            curl -L -f -o "base/$TOOL_NAME" "$DOWNLOAD_URL"
            chmod +x "base/$TOOL_NAME"
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME has been updated to $LATEST_TAG"
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      # --- مرحله کامیت کردن تغییرات ---
      - name: Commit and push updates
        if: steps.update_xray.outputs.updated == 'true' || steps.update_hysteria.outputs.updated == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Tool Updater)"
          git add base/
          git commit -m "chore(base): Update core tools automatically"
          git push
