name: Update Core Tools

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create base directory if not exists
        run: mkdir -p base

      # --- مرحله ۱: آپدیت Xray-Core ---
      - name: Update Xray-Core
        id: update_xray
        run: |
          TOOL_NAME="xray-core"
          REPO="XTLS/Xray-core"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates..."
          API_RESPONSE=$(curl -s "https://api.github.com/repos/$REPO/releases/latest")
          LATEST_TAG=$(echo "$API_RESPONSE" | jq -r '.tag_name')
          
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" == "null" ]; then
            echo "Error: Could not find latest version for $TOOL_NAME."
            exit 1
          fi

          echo "Latest version is: $LATEST_TAG"
          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current version is: $CURRENT_VERSION"
          
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading..."
            DOWNLOAD_URL=$(echo "$API_RESPONSE" | jq -r '.assets[] | select(.name=="Xray-linux-64.zip") | .browser_download_url')
            
            curl -L -o tool.zip "$DOWNLOAD_URL"
            unzip -o tool.zip xray -d .
            mv xray "base/$TOOL_NAME"
            chmod +x "base/$TOOL_NAME"
            rm tool.zip
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME updated to $LATEST_TAG."
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      # --- مرحله ۲: آپدیت Hysteria 2 Client ---
      - name: Update Hysteria-Client
        id: update_hysteria
        run: |
          TOOL_NAME="hysteria-client"
          REPO="apernet/hysteria"
          VERSION_FILE="base/$TOOL_NAME.version"
          
          echo "Checking for $TOOL_NAME updates..."
          API_RESPONSE=$(curl -s "https://api.github.com/repos/$REPO/releases/latest")
          LATEST_TAG=$(echo "$API_RESPONSE" | jq -r '.tag_name')
          
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" == "null" ]; then
            echo "Error: Could not find latest version for $TOOL_NAME."
            exit 1
          fi

          echo "Latest version is: $LATEST_TAG"
          CURRENT_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")
          echo "Current version is: $CURRENT_VERSION"
          
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found! Downloading..."
            DOWNLOAD_URL=$(echo "$API_RESPONSE" | jq -r '.assets[] | select(.name=="hysteria-linux-amd64") | .browser_download_url')

            curl -L -f -o "base/$TOOL_NAME" "$DOWNLOAD_URL"
            chmod +x "base/$TOOL_NAME"
            
            echo "$LATEST_TAG" > "$VERSION_FILE"
            echo "$TOOL_NAME updated to $LATEST_TAG."
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "$TOOL_NAME is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      # --- مرحله ۳: کامیت کردن تغییرات ---
      - name: Commit and push updates
        if: steps.update_xray.outputs.updated == 'true' || steps.update_hysteria.outputs.updated == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Tool Updater)"
          git add base/
          git commit -m "chore(base): Update core tools"
          git push
